### ISSUE TITLE
Update disable-emoji-mess function to remove DNS prefetch for emojis

### ISSUE THREAD

**Issue by kimbaudi** [taniarascia/wp-functions#15]
When removing emojis, the DNS prefetch for emojis (`<link rel='dns-prefetch' href='//s.w.org' />`) should also be removed. This can be accomplished by adding the following line to `function disable_wp_emojicons()`:

```php
add_filter( 'emoji_svg_url', '__return_false' );
```

Found this on [wordpress.stackexchange](http://wordpress.stackexchange.com/a/185578/109650)

**Comment by taniarascia** [comment]
I added this in.
