### ISSUE TITLE
Custom Login Logo URL locaiton? 

### ISSUE THREAD

**Issue by TomLewis** [taniarascia/wp-functions#2]
After setting the custom logo (that works thanks!) it still links to wordpress.org, can this be set with the same function? if not how can we do it?

**Comment by taniarascia** [comment]
Looks like this code should work:

``` php
function custom_login_url() {
return get_bloginfo( 'url' );
}
add_filter( 'login_headerurl', 'custom_login_url' );
```

`return get_bloginfo('url');` can change to `return 'http://example.com'`.

**Comment by TomLewis** [comment]
Partially works, it truncates the .com from the end of the URL I set.

**Comment by taniarascia** [comment]
I just tested it out and it works. It's basing it off the URL you have set in your database.

**Comment by TomLewis** [comment]
This does work! Not sure what I did wrong at first, Alas there is still an Alt tag hover over tag on the image, can that also be set?
